@startuml
'https://plantuml.com/sequence-diagram

actor User

User -> Interface : Вибір категорії величини
User -> Interface : Введення числового значення
User -> Interface : Вибір величин
User -> Interface : Кнопка "Convert"
Interface -> SystemController : Трігер перевірки умов
SystemController -> SystemController: Перевірка даних
alt failure
    SystemController --> Interface : Input error
    Interface --> User : Error Window
else success
    SystemController --> Interface : All is fine
        Interface --> User : Result window

end


@enduml