@startuml
'https://plantuml.com/sequence-diagram

actor User

User -> SystemMain: Запуск додатку
SystemController --> SystemMain : Отримання логіки інтерфейсу
SystemFXML <- SystemMain : Запит на відкриття файлу розмітки
SystemFXML --> SystemMain : Отримання розмітки додатку
SystemMain --> User: Відображення інтерфейсу




@enduml